#!/usr/bin/env node
var exec = require('child_process').exec;
var config = require('./config');
var processes = [];

pushItRealGood();

function pushItRealGood() {
  Promise.all([playMusic(), gitPush(), printLyrics()]).then(function(output) {
    console.log(output[1]);
    process.exit();
  }).catch(function(err) {
    console.error(err);
    processes.forEach(function(child) {
      child.kill('SIGKILL');
    });
    process.exit(1);
  });
}

function playMusic() {
  return promisify(config.playMusic());
}

function gitPush() {
  var args = process.argv.slice(2);
  return promisify(config.gitPush(args));
}

function printLyrics() {
  return Promise.all(config.lyrics().map(function(lyric) {
    return new Promise(function(resolve) {
      setTimeout(function() {
        resolve(console.log(lyric.lyric));
      }, lyric.timeout);
    });
  }));
}

function promisify(command) {
  return new Promise(function(resolve, reject) {
    var child = exec(command, function(err, _, out) {
      if (err) return reject(err);
      resolve(out);
    });
    processes.push(child);
  });
}
